### ISSUE TITLE
[Documentation] Unable to add references

### ISSUE THREAD

**Issue by WeldFire** [risk-of-thunder/R2Wiki#10]
When following the guide listed here: [In Depth First Mod](https://github.com/risk-of-thunder/R2Wiki/wiki/%5BIn-depth%5D-First-mod#step-3--setting-up-your-project)
on step 3 when trying to import the missing references, I get a "The reference is invalid or unsupported." error.

I'm using the latest BepInEx library, and VS Community 2019 as described here [Baby's First Mod](https://github.com/risk-of-thunder/R2Wiki/wiki/Baby's-First-Mod#building-the-exampleplugin)

Are there any troubleshooting steps that can be followed to resolve this issue?

**Comment by harbingerofme** [comment]
You probably still have references to files with the same name in your csproj. Delete all old references first and then try reimporting them.

**Comment by WeldFire** [comment]
That was it!
Removing the old references and then re-importing them did the trick, thank you harbingerofme!
