### ISSUE TITLE
Custom UI not working

### ISSUE THREAD

**Issue by GitCat3** [risk-of-thunder/R2Wiki#12]
when I try to make my custom UI using the page "Adding UI elements to your mod," I get a bunch of errors saying "namespace HUD could not be found," and also, "GameObjectReference does not exist in the current context"

**Comment by harbingerofme** [comment]
Are you sure you are referencing the right libraries? I reckon it's part of the `UnityEngine.UI.dll`

**Comment by GitCat3** [comment]
I figured out all of these previous errors, but inside of MyFunc, the line hud = self; gets an error that says, "Cannot implicitly convert type 'RoR2.UI.HealthBar' to 'RoR2.UI.HUD'"

**Comment by KingEnderBrine** [comment]
Changed hook on a wiki page to `On.RoR2.UI.HUD.Awake` instead of `On.RoR2.UI.HealthBar.Awake`.
