### ISSUE TITLE
Prefabs page is outdated

### ISSUE THREAD

**Issue by Auuki** [risk-of-thunder/R2Wiki#16]
The mod mentioned on the following page doesn't seem to work anymore. Would be great to know an alternative or get the zip updated if possible.

https://github.com/risk-of-thunder/R2Wiki/wiki/Prefabs-and-reading-their-values

**Comment by xiaoxiao921** [comment]
https://github.com/risk-of-thunder/R2Wiki/wiki/Prefabs-and-reading-their-values
