### ISSUE TITLE
FAQ page doesn't point anywhere

### ISSUE THREAD

**Issue by Dragas** [risk-of-thunder/R2Wiki#2]
When clicked, the link takes you to create a page.

**Comment by xiaoxiao921** [comment]
Fixed.
For your information, the wiki is a community driven one, so if you think you could fix it yourself, do not hesitate to try to edit the page. ;)

**Comment by Dragas** [comment]
Personally I am a paranoid man. The current approach does not seem to prevent anyone from just waltzing in and changing all the links to redirection chains and clickjack the readers, hence why I consider "everyone is editing" approach bad. I wonder if you can configure github to send you a notification that wiki was edited at all.

Personally, I suggest using the pull request approach instead. Github already features an in-browser editor and there is no need for git to edit wiki-like repositories. But that's just me.

**Comment by Paddywaan** [comment]
That would require someone to aprove all PR's, honestly I would not like that task considering during certain periods the wiki can be heavily updated with multiple small changes by lots of different users. There have been no malicious actions as of yet, and there is likely no reason to change that considering everyone acts in good faith thus far. We are more productive with it the way it stands IMO.
