### ISSUE TITLE
Link on wiki for BepInEx on Linux points to wrong location

### ISSUE THREAD

**Issue by mkwsnyder** [risk-of-thunder/R2Wiki#20]
The ["If you are installing on Linux please use this guide." link](https://risk-of-thunder.github.io/R2Wiki/Playing/Getting-Started/#bepinex) is broken/goes to the wrong location (I assume the old location).

It's on line 202 of [/docs/Playing/Getting-Started.md](https://github.com/risk-of-thunder/R2Wiki/blob/master/docs/Playing/Getting-Started.md?plain=1#L202)

**Comment by xiaoxiao921** [comment]
Pushed an update to the Getting Started page that should fix it, if you have a better way of finding the user.reg file manually do not hesitate to change the page (anyone can edit the wiki)
