### ISSUE TITLE
missing using directive or assembly reference

### ISSUE THREAD

**Issue by DoppelKakao** [risk-of-thunder/R2Wiki#4]
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0246	The type or namespace name 'BepInEx' could not be found (are you missing a using directive or an assembly reference?)	PersonalizedItems	C:\Users\basti\source\repos\PersonalizedItems\PersonalizedItems\PersonalizedItems.cs	2		Active
I have no clue how to fix this. I tried to clean it and rebuild it but nothing is working.

**Comment by harbingerofme** [comment]
We'd love to help you out over at [our discord](https://discord.gg/5MbXZvd). But it looks like a simple reference error. Check your `.csproj` file and make sure the bepInEx assembly is at the place the project expects it to. otherwise make sure the reference is added.
