### ISSUE TITLE
Write-up reflection

### ISSUE THREAD

**Issue by Paddywaan-zz** [risk-of-thunder/R2Wiki#5]
Stop people whining in discord

**Comment by Paddywaan** [comment]
First pass complete

**Comment by Paddywaan** [comment]
> TwinerToday at 13:52

> The example for methods is kinda bad imo
> you're demonstrating calling a setter and that may confuse less experienced people into thinking they can only work with properties and fields and their related methods
> I would atleast make some additional Methods examples
> an example of one that returns void, one that takes multiple parameters
> I don't see anything wrong overall
