### ISSUE TITLE
Remove outdated/duplicated documentation

### ISSUE THREAD

**Issue by NotTsunami** [risk-of-thunder/R2Wiki#6]
There are 4 pages covering how to create skills, all with different code and similar context:

https://github.com/risk-of-thunder/R2Wiki/wiki/Custom-Skill-Creation-&-Adding-skills
https://github.com/risk-of-thunder/R2Wiki/wiki/Adding-alternate-skills
https://github.com/risk-of-thunder/R2Wiki/wiki/Creating-custom-skills
https://github.com/risk-of-thunder/R2Wiki/wiki/Custom-Skill-Creation

**Comment by xiaoxiao921** [comment]
Hi, i went ahead and removed the last 3 pages entry.
Please know that the wiki is open to everyone for editing.

**Comment by NotTsunami** [comment]
Didn't want to remove any correct information unintentionally, thanks!
