### ISSUE TITLE
[Documentation] How to change minion skins such as turret for the engi

### ISSUE THREAD

**Issue by RuneMasterGaming** [risk-of-thunder/R2Wiki#7]
There is currently very little to go off of.

**Comment by KingEnderBrine** [comment]
I didn't try it, but there is `MinionSkinReplacements` field in `SkinDef. You should be able to do something like that: 
```
MinionSkinReplacements = new SkinDef.MinionSkinReplacement[]
{
    minionBodyPrefab = turretBodyPrefab, // You can find prefab in `BodyCatalog`
    minionSkin = turretSkinDef // Your `SkinDef` instanse for turret
}
```

**Comment by RuneMasterGaming** [comment]
That doesn't seem to work. The console doesn't throw any errors either, it just stays as the default skin.

**Comment by KingEnderBrine** [comment]
Huh, I will try to do this myself later.

**Comment by Reinms** [comment]
You need to actually give the skin to the engineer turret prefab too. The minionSkinReplacement is just telling it which one to use.

**Comment by RyanPallesen** [comment]
This is now available in RyanSkinAPI if that is desired.
The issue is that you need to call SkinCatalog.Init again as it uses a seperate copy from bodycatalog.
