### ISSUE TITLE
[Documentation] "Vanilla and Modded installs" launch parameters

### ISSUE THREAD

**Issue by MrTipson** [risk-of-thunder/R2Wiki#9]
I attempted to set things up but things didn't work as expected. Turns out that my directory had an extra folder called `r2modman` before the rest of the `doorstop-target` path, making the whole (now working) launch options\
`--doorstop-enable true --doorstop-target r2modman\BepInEx\core\BepInEx.Preloader.dll`

Note that all of my mod related things were set up by the mod manager.

Can anyone else confirm this behaviour? If so, it might be a smart move to add a note to the wiki.

**Comment by xiaoxiao921** [comment]
The wiki page is correct. When using r2modman you arent supposed to launch the game through steam but through the r2modman itself.
The wiki page is for people that want to launch vanilla when using manual install
